version: '3.8'

services:
  app:
    container_name: 'basic-registration-app'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      - db

  db:
    container_name: 'basic-registration-db'
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
          - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
